spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:54321}/${POSTGRES_DB:spring-db}
    username: ${POSTGRES_USER:spring-user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    show-sql: true
    generate-ddl: true
